sudo: required
services:
    - docker

before_install:
    - docker build -t karthikkoti/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true karthikkoti/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket: "elasticbeanstalk-us-east-2-901306329935"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
        
