sudo: required
services:
    - docker


before_install:
    - docker build -t karthikkoti/docker-react -f Dockerfile.dev .

script:
    - docker run karthikkoti/docker-react npm run test -- --coverage
